### ISSUE TITLE
Status of translation

### ISSUE THREAD

**Issue by fhemberger** [iojs/iojs-de#16]
### Website
- [x] index (https://github.com/iojs/website/commit/cf79c937f39873dec01afe9ea7fc3decd4a39afd)
- [x] FAQ (https://github.com/iojs/website/commit/cf79c937f39873dec01afe9ea7fc3decd4a39afd, last paragraph missing)
- [x] ES6 (done, see https://github.com/iojs/iojs-de/issues/14)
### Blogposts on Medium
- [x] [io.js Week of February 6th 2015](https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4): (see [iojs.github.io/iojs-de/](http://iojs.github.io/iojs-de/2015/02/05/iojs-week-of-february-6th-2015.html))
- [ ] [io.js and a node.js Foundation](https://medium.com/@iojs/io-js-and-a-node-js-foundation-4e14699fb7be) (see #13)
- [ ] [io.js Week of February 20th 2015](https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980) (see #19)
### Misc
- [x] io.js OS X installer (see: https://github.com/fhemberger/io.js/commit/65ba54ec0eb112ce040415ac2b3b321b8e38b5d1, waiting for  https://github.com/iojs/io.js/pull/776 to land first)
- [x] io.js Windows installer (see: https://github.com/iojs/io.js/pull/888)
- [x] Roadmap presentation (see: https://github.com/fhemberger/roadmap/commit/8d3ecb786835108bb29c6546f99ddc9c31490c04)

**Comment by ghost** [comment]
what about recent patch notes?

**Comment by fhemberger** [comment]
What do you mean?

**Comment by ghost** [comment]
I mean, the situation about patch notes. When I browse iojs.org and choose Deutsch, then I see only English change logs. Is that what we want or tolerate? Sure thing the pace of releasing new iojs versions is very high and they have much more contributors than we have translators. Thats why I'm asking.

**Comment by fhemberger** [comment]
Uh no, I won't translate Changelogs. That doesn't make much sense (it's too easy to unwillingly alter the exact meaning of a very technical description) and is too much work.

**Comment by ghost** [comment]
thanks, that was my question about.

**Comment by fhemberger** [comment]
@iojs/iojs-de It has been really quiet around here lately. Is there still interest in continuing translations? If so: How should we proceed?

**Comment by ghost** [comment]
Still interested.
I think reviewing current content on iojs.org and check if content is up to
date (new content, removed content, modified content).
Roadmap is open. Medium? TBH Medium posts translations are useless unless
published on Medium again.

Maybe we can start on planing a iojs_de meetup. Or help people hosting
meetups in town.
Maybe we could create (mini) tutorials.
Talk to Golem, Heise, etc.

**Comment by fhemberger** [comment]
Okay, so let's drop http://iojs.github.io/iojs-de/.

I don't think that dedicated io.js meetups make sense at the moment (the same as dedicated Node.js events). You don't get enough content focussed on that particular topic that will enable you to host a regular meetup (I've been running a JavaScript user-group for over three years now, I know those problems _g_).

It would be great if you could review [my translation of the roadmap](https://github.com/fhemberger/roadmap/commit/8d3ecb786835108bb29c6546f99ddc9c31490c04)? I just finished it and want to submit the PR to get this finally out of the door.

My own focus has been shifting lately from translation work to general website stuff, but I still keep an eye on the translation efforts regarding the OSX and Windows installer, once the ground work required has been merged into master.

**Comment by ghost** [comment]
Roadmap looks really good. Commented and created a PR to your fork too.

I am doing react.js very much the whole time. io.js runs in background (webpack, gulp, browser-sync) and I switched to atom.io almost completely too. Thats why I think a iojs_de meetup could be a platform for js topics. Because iojs is a platform (at least I understand it that way).

I saw your Windows installer related commits. But I am not a consumer of your code. I am running English OSX and I've installed iojs via nvm. My corporate Windows machine runs in English mode as well.

**Comment by fhemberger** [comment]
I'm closing this, we'll need a new issue for the upcoming `new.nodejs.org` website.
